### ISSUE TITLE
Documentation Enhancement: Token Information

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Package-Builder#155]
Would it be possible to add more information on how to obtain/use the required `.pslmodels_anaconda_token`? I've been searching through old issues in the repo and I believe that I've been able to piece together enough information, but it would be nice to have a few lines in the README about it. I would make this enhancement myself but I believe it would be better to come from someone with more experience using this package.

**Comment by martinholmer** [comment]
Anderson,

Unzip the attached zip file in your home directory.

Best wishes, Martin

**Comment by martinholmer** [comment]
@andersonfrailey asked:
> Would it be possible to add more information on how to obtain/use the required `.pslmodels_anaconda_token` file?

Yes.  I'll add something on that soon.

**Comment by martinholmer** [comment]
Package-Builder issue #155 has been resolved by the merge of pull request #156.
