### ISSUE TITLE
Add support for conda-forge packages

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/Package-Builder#166]
Per #165, support for conda-forge packages should be added to Package-Builder. [Conda-forge](https://conda-forge.org/) is one of the largest community-maintained conda channels. Thus, packages that are built by `pbrelease` should be allowed to depend on packages from there. 

I'm happy to take a crack at making these changes. I think it should be as simple as adding a `conda config --add channels conda-forge` when `pbrelease` is run if the channel is not already there. The channel could then be removed after the build if it the channel is not listed at the beginning of the run.

**Comment by martinholmer** [comment]
As @hdoupe pointed out in the conversation around pull request #168, enhancing Package-Builder is unnecessary.  Pull request #169 shows how to add non-default channels using the `conda config` command.
