### ISSUE TITLE
Add support for 3.8

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/Package-Builder#174]
Currently Package-Builder only builds for 3.5-3.7:

https://github.com/PSLmodels/Package-Builder/blob/87cc8a36bbe82172d6f73b4a8ed5f18ed4883d14/pkgbld/release.py#L16

**Comment by hdoupe** [comment]
cc https://github.com/PSLmodels/Tax-Calculator/issues/2448 @maxghenis

**Comment by MaxGhenis** [comment]
This also just caused a snag trying to install OG-USA into my base conda environment, since I'm on 3.8.
