### ISSUE TITLE
Switching to PSL Anaconda channel

### ISSUE THREAD

**Issue by Peter-Metz** [PSLmodels/Package-Builder#98]
@martinholmer I have created a new Anaconda organization called [PSL](https://anaconda.org/psl), so I think we should be ready to switch over the various packages from the OSPC Anaconda channel to the PSL channel. I am happy to open a PR to start this process, but wanted to check in with you before doing so to make sure we are on the same page.

cc @MattHJensen @hdoupe @andersonfrailey

**Comment by martinholmer** [comment]
@Peter-Metz,  After discussing your attempt to create a PSL channel to the Anaconda Cloud, I think what you are trying to do is hopeless.  (But I hope I'm wrong in that view.)  You said that the Anaconda Cloud (AC) user name `psl` was already taken, so you created an AC user named `policy-simulation-library`.  Each AC user automatically gets an AC channel with the same name as the user.  For example, the `ospc` AC user has the `ospc` channel.  That would suggest that the pre-existing `psl` user already has the `psl` channel.  

I doubt whether having the `policy-simulation-library` AC user create an organization named PSL is going to work around the problem that the pre-existing `psl` user already has the `psl` channel.  Here is what the AC docs say about uploading packages to an organization:
<img width="928" alt="screen shot 2018-11-08 at 9 00 13 am" src="https://user-images.githubusercontent.com/12170745/48203280-103cec00-e335-11e8-860d-1085fa2db432.png">
So, aren't we going to run into the same problem: the `--user PSL` is going to try to upload on the `PSL` channel, which is already owned by the pre-existing `psl` AC user.

I've been able to build and upload packages for the current version of Tax-Calculator using the `P-S-L` channel, which is owned by the new `p-s-l` AC user.  You can confirm that by executing this command:
```
conda install -c P-S-L taxcalc
```
Shall we just go with the `p-s-l` AC user and its `P-S-L` channel?

When the Anaconda help person calls back, be sure to ask questions about how to **move** all the existing packages in the `ospc` AC account to the new account.

@MattHJensen

**Comment by Peter-Metz** [comment]
>So, aren't we going to run into the same problem: the --user PSL is going to try to upload on the PSL channel, which is already owned by the pre-existing psl AC user.

You certainly may be right, but I am still holding out some hope since the [PSL](https://anaconda.org/psl) organization was created yesterday (by me). The customer support rep said he would look into deleting the existing `PSL` organization, in which case we could try creating a new `PSL` organization with the `p-s-l` user. I'm not sure this will work for the reasons you bring up, but it's worth a try. I'll let you know when I hear something.

>When the Anaconda help person calls back, be sure to ask questions about how to move all the existing packages in the ospc AC account to the new account.

Happy to do this.

@martinholmer

**Comment by Peter-Metz** [comment]
I finally got in touch with the Anaconda help person, and the PSL organization should now be [available](https://anaconda.org/psl) for us. I hope it's not too late to change the name of the channel.

I also asked about moving packages between accounts and he said we have two options:

1. Re-upload the packages
2. Use the "anaconda copy" command with the Anaconda CLI. Documentation [here](http://docs.anaconda.com/anaconda-repository/user-guide/tasks/pkgs/copy-pkg/).

@martinholmer @MattHJensen

**Comment by martinholmer** [comment]
@Peter-Metz said in Package-Builder issue #98:
> I finally got in touch with the Anaconda help person, and the PSL organization should now be [available]((https://anaconda.org/psl) ) for us.

Thanks, but when I click on the `available` link (which is to https://anaconda.org/psl), I get this page:

<img width="1263" alt="screen shot 2018-11-14 at 5 11 36 pm" src="https://user-images.githubusercontent.com/12170745/48516222-cd957b00-e830-11e8-81ba-5af7854c9632.png">

Am I doing something wrong?

In any case, it seems that the Policy Simulation Library is standardizing on `PSLmodels` (rather than `PSL`) as the web URL, Anaconda channel, twitter account, etc.

@MattHJensen @hdoupe @andersonfrailey

**Comment by Peter-Metz** [comment]
>Am I doing something wrong?

Not at all - the point of sharing that link was to show that the `PSL` organization had, in fact, been removed so we can make a `PSL` channel if we choose to do so. Of course I am fine with sticking with `PSLmodels` as well.

@martinholmer

**Comment by martinholmer** [comment]
@Peter-Metz said:
> the point of sharing that link was to show that the PSL organization had, in fact, been removed so we can make a PSL channel if we choose to do so. Of course I am fine with sticking with PSLmodels as well.

Oh, OK.  Sorry I misunderstood.

**Comment by martinholmer** [comment]
@Peter-Metz,  Given the course of events, my original notion that the new Anaconda Cloud channel Policy Simulation Library model packages would be named `PSL` has been superseded by a better name: `PSLmodels`.  And we now have a working Anaconda user and channel with that new name.

Given all this, perhaps you should delete the Anaconda user you created recently.
Didn't you say that the AC user was called `policy-simulation-library`?  Thanks.

**Comment by Peter-Metz** [comment]
>perhaps you should delete the Anaconda user you created recently.

Will do, @martinholmer.

**Comment by martinholmer** [comment]
@MattHJensen said nearly four weeks ago:
> It would be nice to sit on the PSL channel if possible.

I presume that @Peter-Metz did not delete the PSL channel.  He and Matt can decide when to do that.
Meanwhile, we're using the `PSLmodels` channel to the Anaconda Cloud to distribute PSL model packages.
